### model
model_name_or_path: tvq_models
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
train_from_scratch: false
# print_param_status: true
deepspeed: configs/ds_config_lv3.json

### dataset
dataset_dir: dataset_path
dataset: dataset
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 4

### output
output_dir: exp_output_path
logging_steps: 1
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1e-5
num_train_epochs: 1
lr_scheduler_type: warmup_stable_decay
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500